# name: Build CyberChatBotGUI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [Release]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore dependencies
      run: msbuild CyberChatBotGUI.sln /t:Restore /p:Configuration=${{ matrix.configuration }}

    - name: Build solution
      run: msbuild CyberChatBotGUI.sln /p:Configuration=${{ matrix.configuration }}

    - name: Upload Build Output
      uses: actions/upload-artifact@v4
      with:
        name: BuildOutput
        path: YourProjectDirectory\bin\Release\

